apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gopal-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /api/a
        pathType: Prefix
        backend:
          service:
            name: backend-a
            port:
              number: 80
      - path: /api/b
        pathType: Prefix
        backend:
          service:
            name: backend-b
            port:
              number: 80